{{- if .Values.databaseSchema }}
apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    scheme: postgres
    host: postgresql-{{ .Values.env }}
    user: postgres
    passwordFrom:
      secretKeyRef:
        key: postgres-password
        name: postgresql-{{ .Values.env }}
    database: postgres
    port: 5432
    parameters:
      sslmode: disable
  schema:
    sql: |
      {{ .Values.databaseSchema }}
{{- end }}