stages:
  - name: test
    config:
      quotas:
        cpuRequest: 4
    additionalObjects:
      enabled: true
      list:
        - kind: Secret
          apiVersion: v1
          metadata:
            name: sample-secret
            namespace: aaa-3-test
            annotations:
              kubernetes.io/service-account.name: pipeline-builder
          data:
            password: MTIzNDU2Cg==
          type: Opaque

  - name: uat
    additionalObjects: {}
  - name: prod
    additionalObjects: {}